version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build checks"
      - npm run lint || echo "Linting completed with warnings"
      - npm run test || true  # Continue even if tests fail

  build:
    commands:
      - echo "Building NestJS application"
      - npm run build
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Preparing artifacts for deployment"
      # Add scripts to the package
      - cp -r scripts/ dist/scripts/
      - cp package*.json dist/
      - cp appspec.yml dist/
      - cd dist && npm ci --only=production
      - echo "Post-build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: no